### PR TITLE
Feat/epic bl3

### PR DESCRIPTION
**Pull request by dafzor**
* Add support for epic borderlands 3

### CODE REVIEW

**Comment by C1rdec** [comment]
By pure curiosity where do you find the game id?

**Comment by dafzor** [comment]
The [README.md](https://github.com/dafzor/bnetlauncher/blob/master/README.md#advanced-adding-new-games-or-custom-cases) goes over how to find the codes in the Advanced section.

**Comment by C1rdec** [comment]
I know but is there a section for Epic that I missed?

**Comment by dafzor** [comment]
It is there: 

> In the case of epic, just create a desktop shortcut and extract the id from the properties, it will be something like: `com.epicgames.launcher://apps/<id will be here>?action=launch&silent=true`

But I've noticed it's not properly formatted making it harder to read, I've updated to fix the formatting and make instructions a bit clearer.

**Pull request merged**
