### PR TITLE
Added support for Diablo IV Beta

### PR DESCRIPTION
**Pull request by Sectimus**

### CODE REVIEW

**Review by dafzor — APPROVED** [review]
Likely that the details wont change after release but looks good

**Comment by Sectimus** [comment]
I noticed the build was created, though it may still need a release. Not sure if the version tag `2.19` was pulled in as I can't see it on the repo.

**Comment by dafzor** [comment]
Will make a release later today. Never got around to making a pipeline for that

**Comment by Sectimus** [comment]
No worries. I assumed I may have missed a step due to the tag not showing. In any case the beta opens in 15 minutes, so I'm gone!  
giphy

**Pull request merged**
